### ISSUE TITLE
Url to the online documentation is broken

### ISSUE THREAD

**Issue by tempfirstuser** [laminas/laminas-cache-storage-adapter-session#14]
This link https://docs.laminas.dev/laminas-cache-storage-adapter-session/ from `README.md` returns 404 page.

**Comment by froschdesign** [comment]
@tempfirstuser 
There will be no separate documentation for this and all other storage adapters. You can find everything about laminas-cache at: https://docs.laminas.dev/laminas-cache/
This means all readme files and repository descriptions of the different storage adapters must be updated.

Thanks for reporting this problem! 👍
